### ISSUE TITLE
Capturing example for pipes and redirections?

### ISSUE THREAD

**Issue by deeplook** [xolox/python-capturer#5]
I am executing shell scripts line by line where lines can contain pipes and redirections. I try to use capturer and subprocess to preserve ANSI escape sequences, but the documentation only gives a simple example. Ideally, I would like to use it with subprocess.getoutput() since it takes the whole line and not a list of line "tokens". Is that possible or something with subprocess.check_output() etc. that preserves ANSI codes?

I've put some test code in this gist: https://gist.github.com/deeplook/cba960baef59817e0a512e46b4b73a0c with a screenshot of the result attached.

<img width="412" alt="screen shot 2018-03-12 at 23 48 29" src="https://user-images.githubusercontent.com/1001778/37313566-18c5846a-2650-11e8-87e9-062ea3f9656e.png">

**Comment by xolox** [comment]
Hi @deeplook, thanks for the feedback and sorry for my late reply (better late than never I guess, if only for other people wondering about similar things and arriving here via search).

It sounds like capturer might be a good fit for what you want to do, but you may be a bit confused about what goes where in using it as a solution, so I'll try to explain as best as I can:

You mention wanting to use [subprocess.getoutput()](https://docs.python.org/3/library/subprocess.html#subprocess.getoutput) but this doesn't make sense to me because half of what this function does is also done by the capturer package (the capturing of output) so it seems to me like all you need is [subprocess.call()](https://docs.python.org/3/library/subprocess.html#subprocess.call).

However you explain your reason for wanting to use [subprocess.getoutput()](https://docs.python.org/3/library/subprocess.html#subprocess.getoutput) as "it takes the whole line and not a list of line tokens". I think you're talking about the distinction between a shell command and the command line of an external program. If I understood this correctly then what you're looking for is something like this:

```python
>>> import subprocess
>>> example_shell_command = """echo '{"result":42}' | pygmentize -l json"""
>>> returncode = subprocess.call(example_shell_command, shell=True)
{"result":42}
>>> returncode
0
```

Note how `shell=True` enables the use of pipes in the command line. The code above immediately prints the colorized output to the terminal. If you want to get a copy of the output that was printed you can use capturer as follows:

```python
>>> import subprocess
>>> from capturer import CaptureOutput
>>> with CaptureOutput() as capturer:
...     shell_cmd = """echo '{"result":42}' | pygmentize -l json"""
...     returncode = subprocess.call(shell_cmd, shell=True)
...
{"result":42}
>>> returncode
0
>>> capturer.get_text()
'{\x1b[38;5;28;01m"result"\x1b[39;00m:\x1b[38;5;241m42\x1b[39m}'
```

To avoid the output from being printed until you say so you can use the ``relay=False`` option:

```python
>>> import subprocess
>>> from capturer import CaptureOutput
>>> with CaptureOutput(relay=False) as capturer:
...     shell_cmd = """echo '{"result":42}' | pygmentize -l json"""
...     returncode = subprocess.call(shell_cmd, shell=True)
...
>>> returncode
0
>>> capturer.get_text()
'{\x1b[38;5;28;01m"result"\x1b[39;00m:\x1b[38;5;241m42\x1b[39m}\n0'
>>> print(capturer.get_text())
{"result":42}
```

I hope this helps!
